env:
  browser: true
  es6: true
  node: true
  # jquery: true
extends: 
  - "eslint:recommended"
  - "plugin:prettier/recommended"
  # - "kentcdodds/possible-errors"
  # - "kentcdodds/es6/possible-errors"
parserOptions:
  sourceType: module
rules:
  eqeqeq:
    - error
    - always
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  "prettier/prettier":
    - error
plugins: [ "prettier" ]

